"""test

Revision ID: 160a85769b49
Revises: 1ef3d63aa980
Create Date: 2022-11-06 02:42:19.860103

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel         #Added later


# revision identifiers, used by Alembic.
revision = '160a85769b49'
down_revision = '1ef3d63aa980'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
