"""init

Revision ID: 1ef3d63aa980
Revises: af0af7e970ec
Create Date: 2022-11-04 12:05:17.912051

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel         #Added later


# revision identifiers, used by Alembic.
revision = '1ef3d63aa980'
down_revision = 'af0af7e970ec'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
