"""init

Revision ID: 34b8b78fd2d2
Revises: 4a4dfb617467
Create Date: 2022-10-20 21:35:10.251830

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel         #Added later


# revision identifiers, used by Alembic.
revision = '34b8b78fd2d2'
down_revision = '4a4dfb617467'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urlinfo', 'clicks')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urlinfo', sa.Column('clicks', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
