"""init

Revision ID: 4a4dfb617467
Revises: ac9a9968d889
Create Date: 2022-10-20 11:41:29.484792

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel         #Added later


# revision identifiers, used by Alembic.
revision = '4a4dfb617467'
down_revision = 'ac9a9968d889'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urlinfo', sa.Column('clicks', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urlinfo', 'clicks')
    # ### end Alembic commands ###
