"""init

Revision ID: 649ef5c78eb4
Revises: 34b8b78fd2d2
Create Date: 2022-10-22 03:29:29.608773

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel         #Added later


# revision identifiers, used by Alembic.
revision = '649ef5c78eb4'
down_revision = '34b8b78fd2d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
