"""test

Revision ID: ac7a50c89d5e
Revises: cbc4af17a65d
Create Date: 2022-11-06 02:50:47.514611

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel         #Added later


# revision identifiers, used by Alembic.
revision = 'ac7a50c89d5e'
down_revision = 'cbc4af17a65d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
