"""init

Revision ID: af0af7e970ec
Revises: 685755295c38
Create Date: 2022-11-04 07:51:50.243006

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel         #Added later


# revision identifiers, used by Alembic.
revision = 'af0af7e970ec'
down_revision = '685755295c38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
