"""test

Revision ID: ba77db4a8907
Revises: ac7a50c89d5e
Create Date: 2022-11-06 02:52:30.033412

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel         #Added later


# revision identifiers, used by Alembic.
revision = 'ba77db4a8907'
down_revision = 'ac7a50c89d5e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
