"""test

Revision ID: c44ac3a3babc
Revises: ba77db4a8907
Create Date: 2022-11-06 02:55:34.343425

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel         #Added later


# revision identifiers, used by Alembic.
revision = 'c44ac3a3babc'
down_revision = 'ba77db4a8907'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
