"""test

Revision ID: cbc4af17a65d
Revises: 160a85769b49
Create Date: 2022-11-06 02:43:00.855985

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel         #Added later


# revision identifiers, used by Alembic.
revision = 'cbc4af17a65d'
down_revision = '160a85769b49'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
